name = "Gerbarium Mods Server"
author = "Gerbarium Team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "523eb19d4618842280323fafe9c3cf7cca410c3cd02944f9959be977cc7cd7e0"

[versions]
fabric = "0.19.2"
minecraft = "1.20.1"
