name = "Gerbarium Mods Server"
author = "Gerbarium Team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "73034e92901d8680fadeba6fed8b773fe81cfc6fcdf2b48814f30bb75f468469"

[versions]
fabric = "0.19.2"
minecraft = "1.20.1"
